site_name: FutureServer文档
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
  palette:
    scheme: default
    primary: blue
plugins:
  - search
nav:
  - 首页: index.md
  - 公告: broad.md
  - 规则: rules.md
  - 用户安全:
      - 处罚（如何解封）: user-safety/punish.md
      - 被盗号了怎么办: user-safety/user-stolen.md
  - 玩法: gameplay.md
  - 铁路(FSRI):
      - 公告: fsri/broad.md
      - 加入: fsri/join.md
      - 人员: fsri/list.md